Base:
    model_root: './checkpoints/'
    workers: 8
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False
    version: 'pytorch'


xDeepFM_Frappe:
    model: xDeepFM
    dataset_id: Frappe
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.1
    net_regularizer: 0.1
    batch_size: 4096
    embedding_dim: 10
    dnn_hidden_units: [400, 400, 400]
    cin_layer_units: [32]
    hidden_activations: relu
    net_dropout: 0.1
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

xDeepFM_Movielens:
    model: xDeepFM
    dataset_id: Movielens
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.01
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    dnn_hidden_units: [400, 400, 400]
    cin_layer_units: [32,32,32,32]
    hidden_activations: relu
    net_dropout: 0.4
    batch_norm: True
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'