base_config: ./config/xDeepFM
base_expid: xDeepFM_Movielens
dataset_id: Movielens

dataset_config:
    Movielens:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Movielens/train.h5
        valid_data: ./data/Movielens/valid.h5
        test_data: ./data/Movielens/test.h5

tuner_space:
    cin_layer_units: [[32],[32,32],[32, 32, 32],[32,32,32,32],[32,32,32,32,32],[32,32,32,32,32,32],[32,32,32,32,32,32,32],[32,32,32,32,32,32,32,32]]