Base:
    model_root: './checkpoints/'
    workers: 8
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False
    version: 'pytorch'

LR_base:
    model: LR
    model_root: './checkpoints'
    dataset_id: TBD
    loss: binary_crossentropy
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    regularizer: 0
    batch_size: 10000
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'
    debug: False
    verbose: True