Base:
    model_root: './checkpoints/'
    workers: 8
    verbose: 1
    patience: 2
    pickle_feature_encoder: True
    use_hdf5: True
    save_best_only: True
    every_x_epochs: 1
    debug: False
    version: 'pytorch'


DCN_Frappe:
    batch_norm: false
    layer_norm: False
    batch_size: 4096
    crossing_layers: 8
    dataset_id: Frappe
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.1
    epochs: 100
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    seed: 2021
    shuffle: true
    task: binary_classification


DCN_Movielens:
    batch_norm: false
    layer_norm: False
    batch_size: 4096
    crossing_layers: 8
    dataset_id: Movielens
    debug: false
    dnn_activations: relu
    dnn_hidden_units: [400, 400, 400]
    embedding_dim: 10
    embedding_regularizer: 0.01
    epochs: 100
    every_x_epochs: 1
    learning_rate: 0.001
    loss: binary_crossentropy
    metrics: [logloss, AUC]
    model: DCN
    model_id: DCN_movielens
    model_root: ./checkpoints/
    monitor: {AUC: 1, logloss: -1}
    monitor_mode: max
    net_dropout: 0.1
    net_regularizer: 0
    optimizer: adam
    patience: 2
    pickle_feature_encoder: true
    save_best_only: true
    seed: 2021
    shuffle: true
    task: binary_classification
    use_hdf5: true
    verbose: 1
    version: pytorch
    workers: 8


DCN_Criteo:
    model: DCN
    dataset_id: Criteo
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 1.0e-5
    net_regularizer: 0.1
    batch_size: 4096
    embedding_dim: 10
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    crossing_layers: 3
    net_dropout: 0.1
    batch_norm: False
    layer_norm: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'

DCN_Avazu:
    model: DCN
    dataset_id: Avazu
    loss: 'binary_crossentropy'
    metrics: ['logloss', 'AUC']
    task: binary_classification
    optimizer: adam
    learning_rate: 1.0e-3
    embedding_regularizer: 0.001
    net_regularizer: 0
    batch_size: 4096
    embedding_dim: 10
    dnn_hidden_units: [400, 400, 400]
    dnn_activations: relu
    crossing_layers: 5
    net_dropout: 0.3
    batch_norm: False
    epochs: 100
    shuffle: True
    seed: 2021
    monitor: {'AUC': 1, 'logloss': -1}
    monitor_mode: 'max'