base_config: ./config/DCN
base_expid: DCN_Frappe
dataset_id: Frappe

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Frappe/train.h5
        valid_data: ./data/Frappe/valid.h5
        test_data: ./data/Frappe/test.h5

tuner_space:
    model_root: './checkpoints/'
    crossing_layers: [1,2,3,4,5,6,7,8,9]