base_config: ./config/AutoInt
base_expid: AutoInt+_Criteo
dataset_id: Criteo

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Criteo/train.h5
        valid_data: ./data/Criteo/valid.h5
        test_data: ./data/Criteo/test.h5

tuner_space:
    model_root: './checkpoints/'
    net_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]