base_config: ./config/AutoInt
base_expid: AutoInt+_Frappe
dataset_id: Frappe

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Frappe/train.h5
        valid_data: ./data/Frappe/valid.h5
        test_data: ./data/Frappe/test.h5

tuner_space:
    model_root: './checkpoints/'
    net_dropout: [0, 0.1, 0.2, 0.3, 0.4, 0.5]