base_config: ./config/AFN
base_expid: AFN+_Criteo
dataset_id: Criteo

dataset_config:
    Criteo:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Criteo/train.h5
        valid_data: ./data/Criteo/valid.h5
        test_data: ./data/Criteo/test.h5

tuner_space:
    model_root: './checkpoints/'
    dnn_hidden_units: [[400],[400,400],[400,400,400],[400,400,400,400],[400,400,400,400,400]]