base_config: ./config/AFN
base_expid: AFN+_Frappe
dataset_id: Frappe

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Frappe/train.h5
        valid_data: ./data/Frappe/valid.h5
        test_data: ./data/Frappe/test.h5

tuner_space:
    model_root: './checkpoints/'
    patience: [2,5,10,20,30]
    monitor: [{AUC: 1, logloss: -1},{AUC: 1, logloss: 0},{AUC: 0, logloss: -1}]
