base_config: ./config/AFN
base_expid: AFN+_Frappe
dataset_id: Frappe

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Frappe/train.h5
        valid_data: ./data/Frappe/valid.h5
        test_data: ./data/Frappe/test.h5

tuner_space:
    model_root: './checkpoints/'
    embedding_initializer: ["torch.nn.init.normal_(std=0.1)",
                            "torch.nn.init.normal_(std=0.01)",
                            "torch.nn.init.normal_(std=0.001)",
                            "torch.nn.init.normal_(std=0.0001)",
                            "torch.nn.init.normal_(std=0.00001)",
                            "torch.nn.init.xavier_normal_(gain=0.1)",
                            "torch.nn.init.xavier_normal_(gain=0.3)",
                            "torch.nn.init.xavier_normal_(gain=0.5)",
                            "torch.nn.init.xavier_normal_(gain=0.8)",
                            "torch.nn.init.xavier_normal_(gain=1)",
                            "torch.nn.init.xavier_uniform_(gain=0.1)",
                            "torch.nn.init.xavier_uniform_(gain=0.3)",
                            "torch.nn.init.xavier_uniform_(gain=0.5)",
                            "torch.nn.init.xavier_uniform_(gain=0.8)",
                            "torch.nn.init.xavier_uniform_(gain=1)",
                            "torch.nn.init.uniform_(a=0, b=0.1)",
                            "torch.nn.init.uniform_(a=0, b=0.01)",
                            "torch.nn.init.uniform_(a=0, b=0.001)",
                            "torch.nn.init.uniform_(a=0, b=0.0001)",
                            "torch.nn.init.uniform_(a=0,b=0.00001)"
                            ]