base_config: ./config/AFN
base_expid: AFN_Frappe
dataset_id: Frappe

dataset_config:
    Frappe:
        data_format: h5
        data_root: './data/'
        train_data: ./data/Frappe/train.h5
        valid_data: ./data/Frappe/valid.h5
        test_data: ./data/Frappe/test.h5

tuner_space:
    model_root: './checkpoints/'
    learning_rate: [0.01,0.005,0.001,0.0005,0.0001]